import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import Button from "../components/Button";
import Modal from "../components/Modal";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [displayModal, setDisplayModal] = useState(false);
  const [dataUser, setDataUser] = useState([]);
  const openModal = () => {
    setDisplayModal(true);
  };

  const closeModal = () => {
    setDisplayModal(false);
  };
  console.log(displayModal);

  const getData = async () => {
    const response = await fetch(
      "https://randomuser.me/api/?page=1&results=100"
    );
    const data = await response.json();
    setDataUser(data.results);
  };

  useEffect(() => {
    getData();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Modal Component</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Custom Modal</h1>

        <Button type="primary" onClick={openModal}>
          Open Modal
        </Button>

        {displayModal && (
          <Modal
            data-effect="mfp-zoom-in"
            handleClose={closeModal}
            isOpen={displayModal}
            modalTitle="User List"
          >
            <ul>
              {dataUser.map((item: { email: string }, key: number) => (
                <li key={key}>{item?.email}</li>
              ))}
            </ul>
          </Modal>
        )}
      </main>
    </div>
  );
};

export default Home;
